export const PORT = 3000;


export enum DATABASE_ENV {
DATABASE_USER = "blog",
DATABASE_PASSWORD = "blog-64",
DATABASE_NAME = "blog",
DATABASE_HOST = "localhost",
DATABASE_PORT = "3306"
}

export enum HttpCode {
OK = 200,
CREATED = 201,
NO_CONTENT = 204,
BAD_REQUEST = 400,
UNAUTHORIZED = 401,
FORBIDDEN = 403,
NOT_FOUND = 404,
INTERNAL_SERVER_ERROR = 500
}